language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '2.1.4'
sudo: false
cache: bundler
rvm:
  - 2.7.1
services:
  - postgresql
before_script:
  - psql -c 'create database "rubysg-reboot_test";' -U postgres
  - bin/setup
