# fly.toml app configuration file generated for rubysg-reboot on 2023-08-19T11:29:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rubysg-reboot"
kill_signal = "SIGINT"
kill_timeout = "120s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    BUNDLER_VERSION = "2.4.20"
    NODE_VERSION = "14.5.0"
    RUBY_VERSION = "3.2.1"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  INCLUDES_SCHEDULER = 1
  PORT = "8080"
  SERVER_COMMAND = "bin/rails fly:server"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  auto_stop_machines = false

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
