# fly.toml file generated for rubysg-reboot on 2022-09-24T14:42:40+08:00

app = "rubysg-reboot-worker"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    BUNDLER_VERSION = "2.4.20"
    NODE_VERSION = "14.5.0"
    RUBY_VERSION = "2.7.1"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "8080"
  SERVER_COMMAND = "bin/rails jobs:work"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
